# Generated by Django 3.1.5 on 2021-02-23 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_fusion', '0002_auto_20210222_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico',
            name='icones',
            field=models.CharField(choices=[('lni-cog', 'Engrenagem'), ('lni-stats-up', 'Status'), ('lni-users', 'Usuarios'), ('lni-layers', 'Camadas'), ('lni-mobile', 'Telefone'), ('lni-rocket', 'Foguete')], max_length=12, verbose_name='Icone'),
        ),
    ]
