# Generated by Django 3.1.4 on 2020-12-22 02:08

from django.db import migrations, models

# Criado pois errei o nome do campo 'Idade' ao digitar na primeira vez

class Migration(migrations.Migration):

    dependencies = [
        ('app_centro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='idade',
            field=models.IntegerField(verbose_name='Idade'),
        ),
    ]
