# Generated by Django 3.1.4 on 2020-12-22 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_centro', '0002_auto_20201222_0208'),
    ]

    operations = [
        migrations.CreateModel(
            name='Itens',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_item', models.CharField(max_length=100, verbose_name='Nome')),
                ('code_item', models.CharField(max_length=200, verbose_name='Código')),
                ('preco_item', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Preço')),
            ],
        ),
        migrations.RenameField(
            model_name='user',
            old_name='email',
            new_name='email_user',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='idade',
            new_name='idade_user',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='nome',
            new_name='nome_user',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='sobrenome',
            new_name='sobrenome_user',
        ),
    ]
