# Generated by Django 3.1.4 on 2021-01-14 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ms_core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livros',
            name='estoque',
            field=models.IntegerField(verbose_name='Estoque'),
        ),
    ]
