# Generated by Django 3.1.4 on 2021-01-14 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ms_core', '0002_auto_20210114_0938'),
    ]

    operations = [
        migrations.AddField(
            model_name='livros',
            name='solicitado',
            field=models.BooleanField(default=False, verbose_name='Solicitado?'),
        ),
    ]
